-- @example/core — bootstrap resource for the Full Stack Example.
--
-- Generated by `nextvm build` in real projects. Hand-written here so
-- the example is readable as a reference.

fx_version 'cerulean'
game 'gta5'
lua54 'yes'

author 'NextVM'
description 'Full Stack Example bootstrap'
version '0.1.0'

server_scripts {
	'dist/server/index.js',
}

client_scripts {
	'dist/client/index.js',
}

-- NUI block — appended verbatim from `nui/fxmanifest.nui.lua` produced
-- by @nextvm/vite-plugin-nui on `vite build`.
exec 'nui/fxmanifest.nui.lua'

dependencies {
	'nextvm-banking',
	'nextvm-jobs',
	'nextvm-housing',
	'nextvm-inventory',
	'nextvm-player',
	'nextvm-vehicle',
}
