import { describe, expect, it } from 'vitest'
import { generateServerCfg } from '../server-cfg'

describe('generateServerCfg', () => {
	const baseInput = {
		hostname: 'Test Server',
		maxClients: 32,
		endpoint: '0.0.0.0:30120',
		modules: [
			{ name: 'banking', path: '/abs/banking' },
			{ name: 'jobs', path: '/abs/jobs' },
		],
	}

	it('emits the canonical header + endpoint block', () => {
		const cfg = generateServerCfg(baseInput)
		expect(cfg).toMatch(/Generated by NextVM/)
		expect(cfg).toContain('endpoint_add_tcp "0.0.0.0:30120"')
		expect(cfg).toContain('endpoint_add_udp "0.0.0.0:30120"')
	})

	it('uses the default game build when not specified', () => {
		const cfg = generateServerCfg(baseInput)
		expect(cfg).toContain('sv_enforceGameBuild 3095')
	})

	it('respects an explicit game build', () => {
		const cfg = generateServerCfg({ ...baseInput, gameBuild: 2944 })
		expect(cfg).toContain('sv_enforceGameBuild 2944')
		expect(cfg).not.toContain('sv_enforceGameBuild 3095')
	})

	it('writes one ensure line per module in declared order', () => {
		const cfg = generateServerCfg(baseInput)
		const ensureLines = cfg
			.split('\n')
			.filter((l) => l.startsWith('ensure '))
		expect(ensureLines).toEqual(['ensure banking', 'ensure jobs'])
	})

	it('deduplicates module ensure lines', () => {
		const cfg = generateServerCfg({
			...baseInput,
			modules: [
				{ name: 'banking', path: '/a' },
				{ name: 'banking', path: '/b' },
				{ name: 'jobs', path: '/c' },
			],
		})
		const ensureLines = cfg
			.split('\n')
			.filter((l) => l.startsWith('ensure '))
		expect(ensureLines).toEqual(['ensure banking', 'ensure jobs'])
	})

	it('appends additional resources after the modules', () => {
		const cfg = generateServerCfg({
			...baseInput,
			additionalResources: ['pma-voice', 'oxmysql'],
		})
		expect(cfg).toContain('ensure pma-voice')
		expect(cfg).toContain('ensure oxmysql')
		// Order: framework modules first, then extras
		const bankingIdx = cfg.indexOf('ensure banking')
		const voiceIdx = cfg.indexOf('ensure pma-voice')
		expect(bankingIdx).toBeLessThan(voiceIdx)
	})

	it('quotes the hostname and escapes inner quotes', () => {
		const cfg = generateServerCfg({
			...baseInput,
			hostname: 'Tom\'s "Cool" Server',
		})
		expect(cfg).toContain('sv_hostname "Tom\'s \\"Cool\\" Server"')
	})

	it('includes the license key when provided', () => {
		const cfg = generateServerCfg({ ...baseInput, licenseKey: 'cfxk_abc123' })
		expect(cfg).toContain('sv_licenseKey "cfxk_abc123"')
	})

	it('warns about missing license key when not provided', () => {
		const cfg = generateServerCfg(baseInput)
		expect(cfg).toContain('No license key set')
		expect(cfg).not.toMatch(/sv_licenseKey "/)
	})

	it('emits convars in sorted order with proper formatting', () => {
		const cfg = generateServerCfg({
			...baseInput,
			convars: {
				sv_scriptHookAllowed: false,
				z_custom: 'value with spaces',
				a_number: 42,
				b_simple: 'simple',
			},
		})
		expect(cfg).toContain('set a_number 42')
		expect(cfg).toContain('set b_simple simple')
		expect(cfg).toContain('set sv_scriptHookAllowed 0')
		expect(cfg).toContain('set z_custom "value with spaces"')

		// Verify sort order: a_ < b_ < sv_ < z_
		const aIdx = cfg.indexOf('set a_number')
		const zIdx = cfg.indexOf('set z_custom')
		expect(aIdx).toBeLessThan(zIdx)
	})

	it('boolean true convars become 1, false become 0', () => {
		const cfg = generateServerCfg({
			...baseInput,
			convars: { flag_on: true, flag_off: false },
		})
		expect(cfg).toContain('set flag_on 1')
		expect(cfg).toContain('set flag_off 0')
	})

	it('handles empty modules array gracefully', () => {
		const cfg = generateServerCfg({ ...baseInput, modules: [] })
		const ensureLines = cfg.split('\n').filter((l) => l.startsWith('ensure '))
		expect(ensureLines).toEqual([])
		// Should still have the header and endpoint
		expect(cfg).toContain('endpoint_add_tcp')
	})

	it('always ends with a single trailing newline', () => {
		const cfg = generateServerCfg(baseInput)
		expect(cfg.endsWith('\n')).toBe(true)
		expect(cfg.endsWith('\n\n')).toBe(false)
	})
})
