import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { loadProject, type ResolvedModule } from '@nextvm/build'
import type { Command } from 'commander'
import { cliLog } from '../utils/logger'

/**
 * `nextvm docs` — Generate Markdown reference docs from each module.
 *
 * Concept v2.3, Chapter 25:
 *   "Documentation generated from TSDoc + Zod introspection + hand-written guides"
 *
 * Phase 2 minimum: walk every discovered module, parse its index.ts +
 * router.ts statically, and emit a Markdown file under
 * `<project>/docs/modules/<name>.md` with:
 *   - Description (from package.json)
 *   - Version
 *   - Declared dependencies
 *   - RPC procedures (name + type + input shape)
 *   - Locale key list
 *
 * The output is intentionally hand-readable so the same files can be
 * dropped into a VitePress / Starlight site later.
 */
export function registerDocsCommand(program: Command): void {
	program
		.command('docs')
		.description('Generate Markdown reference docs for every module')
		.option('--out <dir>', 'Output directory (default: docs/modules)', 'docs/modules')
		.action(async (opts: { out?: string }) => {
			try {
				const project = await loadProject()
				const outDir = opts.out ?? 'docs/modules'
				cliLog.header(`Generating docs for ${project.modules.length} module(s)`)

				mkdirSync(outDir, { recursive: true })
				for (const mod of project.modules) {
					const md = renderModuleDoc(mod)
					const file = join(outDir, `${mod.name.replace('@nextvm/', '')}.md`)
					writeFileSync(file, md)
					cliLog.success(`${mod.name} → ${file}`)
				}
				cliLog.success(`Wrote ${project.modules.length} doc file(s) to ${outDir}/`)
			} catch (err) {
				cliLog.error(err instanceof Error ? err.message : String(err))
				process.exit(1)
			}
		})
}

function renderModuleDoc(mod: ResolvedModule): string {
	const description =
		(mod.packageJson.description as string | undefined) ?? '_No description_'
	const indexPath = join(mod.path, 'src', 'index.ts')
	const indexContent = existsSync(indexPath) ? readFileSync(indexPath, 'utf-8') : ''

	const declaredDeps = extractDeclaredDependencies(indexContent)
	const procedures = collectProcedures(mod)
	const locales = collectLocaleKeys(mod)

	const lines: string[] = []
	lines.push(`# ${mod.name}`)
	lines.push('')
	lines.push(description)
	lines.push('')
	lines.push(`**Version:** ${mod.version}`)
	lines.push('')

	if (declaredDeps.length > 0) {
		lines.push('## Dependencies')
		lines.push('')
		for (const dep of declaredDeps) {
			lines.push(`- \`${dep}\``)
		}
		lines.push('')
	}

	if (procedures.length > 0) {
		lines.push('## RPC Procedures')
		lines.push('')
		lines.push('| Name | Type | Input |')
		lines.push('| --- | --- | --- |')
		for (const p of procedures) {
			const inputCell = p.inputZod ? `\`${p.inputZod}\`` : '_(none)_'
			lines.push(`| \`${p.name}\` | \`${p.type}\` | ${inputCell} |`)
		}
		lines.push('')
	}

	if (locales.length > 0) {
		lines.push('## Locales')
		lines.push('')
		for (const l of locales) {
			lines.push(`### \`${l.locale}\` (${l.keys.length} keys)`)
			lines.push('')
			for (const key of l.keys) lines.push(`- \`${key}\``)
			lines.push('')
		}
	}

	lines.push('---')
	lines.push('')
	lines.push(`_Generated by \`nextvm docs\` from ${mod.relativePath}._`)
	return lines.join('\n')
}

function extractDeclaredDependencies(content: string): string[] {
	const match = content.match(/dependencies\s*:\s*\[([^\]]*)\]/)
	if (!match || !match[1]) return []
	return Array.from(match[1].matchAll(/['"]([^'"]+)['"]/g)).map((m) => m[1] as string)
}

interface ProcedureDoc {
	name: string
	type: 'query' | 'mutation'
	inputZod: string | null
}

function collectProcedures(mod: ResolvedModule): ProcedureDoc[] {
	const routerPath = join(mod.path, 'src', 'server', 'router.ts')
	if (!existsSync(routerPath)) return []
	const content = readFileSync(routerPath, 'utf-8')

	const procs: ProcedureDoc[] = []
	const procRegex = /(\w+)\s*:\s*procedure([^,}]*?)\.(query|mutation)\s*\(/gs
	for (const match of content.matchAll(procRegex)) {
		const name = match[1] as string
		const chain = match[2] ?? ''
		const type = match[3] as 'query' | 'mutation'
		const inputMatch = chain.match(/\.input\(\s*([^)]+?)\s*\)/s)
		const inputZod = inputMatch ? inputMatch[1]?.replace(/\s+/g, ' ').slice(0, 100) ?? null : null
		procs.push({ name, type, inputZod })
	}
	return procs
}

interface LocaleDoc {
	locale: string
	keys: string[]
}

function collectLocaleKeys(mod: ResolvedModule): LocaleDoc[] {
	const dir = join(mod.path, 'src', 'shared', 'locales')
	if (!existsSync(dir)) return []
	const result: LocaleDoc[] = []
	for (const file of ['en.ts', 'de.ts']) {
		const path = join(dir, file)
		if (!existsSync(path)) continue
		const content = readFileSync(path, 'utf-8')
		const keys = Array.from(content.matchAll(/['"]([\w.-]+)['"]\s*:/g)).map((m) => m[1] as string)
		result.push({ locale: file.replace('.ts', ''), keys })
	}
	return result
}
