/**
 * Virtual module `virtual:nextvm-nui`.
 *
 * Resolves at build/dev time to a tiny ES module that exposes the
 * resource name + the NextVM-NUI runtime constants. NUI code can then
 * write:
 *
 *   import { resourceName, NuiBrowser } from 'virtual:nextvm-nui'
 *   const bus = new NuiBrowser({ resourceName })
 *
 * without hardcoding the resource name in 12 places.
 */
export interface VirtualModuleSource {
	resourceName: string
	devMode: boolean
}

export const VIRTUAL_ID = 'virtual:nextvm-nui'
export const RESOLVED_VIRTUAL_ID = '\0virtual:nextvm-nui'

export function buildVirtualModuleSource(opts: VirtualModuleSource): string {
	return [
		`// Generated by @nextvm/vite-plugin-nui — do not edit by hand.`,
		`export const resourceName = ${JSON.stringify(opts.resourceName)}`,
		`export const devMode = ${opts.devMode ? 'true' : 'false'}`,
		// Re-export NuiBrowser for convenience. The NUI side declares`,
		`// @nextvm/nui as a regular dependency so this resolves normally.`,
		`export { NuiBrowser } from '@nextvm/nui/browser'`,
	].join('\n')
}
