blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/nextvm-official/nextvm/tree/main/docs
    about: Read the docs before opening an issue.
  - name: Discussions
    url: https://github.com/nextvm-official/nextvm/discussions
    about: Ask questions, share ideas, get help from the community.
