import type { ServerCfgInput } from './types'

/**
 * Generate the contents of `server.cfg.nextvm` from a structured input.
 *
 * The output is intentionally written to `server.cfg.nextvm` (NOT
 * `server.cfg`) so we never overwrite a user's hand-managed config.
 * The runner spawns FXServer with `+exec server.cfg.nextvm` so the
 * generated file is loaded explicitly.
 *
 * Pure function — no filesystem, no env reads. The caller is responsible
 * for getting the license key out of the environment if needed.
 */
export function generateServerCfg(input: ServerCfgInput): string {
	const lines: string[] = []

	lines.push('# Generated by NextVM. Do not edit by hand — changes will be')
	lines.push('# overwritten on the next `nextvm dev --serve` or `nextvm serve` run.')
	lines.push('# Source of truth: <project-root>/nextvm.config.ts')
	lines.push('')

	// --- Endpoints ---
	lines.push('# Network')
	lines.push(`endpoint_add_tcp "${input.endpoint}"`)
	lines.push(`endpoint_add_udp "${input.endpoint}"`)
	lines.push('')

	// --- Game build + script hook ---
	lines.push('# Game build')
	lines.push('sv_scriptHookAllowed 0')
	lines.push(`sv_enforceGameBuild ${input.gameBuild ?? 3095}`)
	lines.push('')

	// --- Convars (free-form set <key> <value>) ---
	if (input.convars && Object.keys(input.convars).length > 0) {
		lines.push('# Convars from nextvm.config.ts → fxserver.convars')
		const sortedKeys = Object.keys(input.convars).sort()
		for (const key of sortedKeys) {
			const value = input.convars[key]
			lines.push(`set ${key} ${formatConvarValue(value!)}`)
		}
		lines.push('')
	}

	// --- Dev-bridge wiring ---
	// The runtime-server's dev bridge uses GetConvar('nextvm_dev_trigger')
	// to locate the dev-trigger file. Without this convar the bridge
	// falls back to a relative path which only works when FXServer's
	// cwd happens to equal the project root.
	if (input.devTriggerPath) {
		lines.push('# NextVM dev bridge — absolute path to dev-trigger.json')
		lines.push(`set nextvm_dev_trigger "${escapeQuotes(input.devTriggerPath)}"`)
		lines.push('')

		// Note: ACL grants for ensure are no longer needed here because
		// the runner sends `ensure <name>` directly via FXServer's stdin
		// pipe, which has console-level ACL. The old file-based bridge
		// (ExecuteCommand from inside a resource) needed per-resource
		// `add_ace` entries, but stdin does not.
	}

	// --- License key (only if provided) ---
	if (input.licenseKey) {
		lines.push('# License — read from CFX_LICENSE_KEY env var at generation time')
		lines.push(`sv_licenseKey "${input.licenseKey}"`)
		lines.push('')
	} else {
		lines.push('# No license key set — server will run in offline mode.')
		lines.push('# Set CFX_LICENSE_KEY in your .env to enable online play.')
		lines.push('')
	}

	// --- Hostname + max clients ---
	lines.push('# Server identity')
	lines.push(`sv_hostname "${escapeQuotes(input.hostname)}"`)
	lines.push(`sv_maxclients ${input.maxClients}`)
	lines.push('')

	// --- NextVM modules (in dependency order) ---
	if (input.modules.length > 0) {
		lines.push('# NextVM modules (dependency-ordered)')
		const seenModules = new Set<string>()
		for (const mod of input.modules) {
			if (seenModules.has(mod.name)) continue
			seenModules.add(mod.name)
			lines.push(`ensure ${mod.name}`)
		}
		lines.push('')
	}

	// --- Additional user-managed resources ---
	const extras = input.additionalResources ?? []
	if (extras.length > 0) {
		lines.push('# Additional resources from nextvm.config.ts → fxserver.additionalResources')
		const seenExtras = new Set<string>()
		for (const name of extras) {
			if (seenExtras.has(name)) continue
			seenExtras.add(name)
			lines.push(`ensure ${name}`)
		}
		lines.push('')
	}

	return `${lines.join('\n').trimEnd()}\n`
}

function formatConvarValue(value: string | number | boolean): string {
	if (typeof value === 'boolean') return value ? '1' : '0'
	if (typeof value === 'number') return String(value)
	// String — wrap in quotes if it contains whitespace
	if (/\s/.test(value)) return `"${escapeQuotes(value)}"`
	return value
}

function escapeQuotes(value: string): string {
	return value.replace(/"/g, '\\"')
}
